In [1]:
import numpy as np
data=np.array([10,20,30,40,50])
print(np.mean(data))

30.0


In [4]:
import numpy as np
data=np.array([10,20,30,40,50])
print(np.median(data))

30.0


In [5]:
import numpy as np
from scipy import stats
data=np.array([10,20,30,10,40,50])
print(stats.mode(data))

ModeResult(mode=np.int64(10), count=np.int64(2))


In [24]:
import numpy as np
data=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(data.ndim)

2


In [25]:
import numpy as np
data=np.array([[[10,20,30,40,50],[60,70,80,90,100]]])
print(data.ndim)

3


In [19]:
data=np.arange(1,100)
print(data)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [30]:
data=[10,20,30,40,50]
data[::-1]

[50, 40, 30, 20, 10]

In [39]:
data=np.arange(1,10).reshape(3,3)
print(data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
data=np.arange(1,26).reshape(5,5)
print(data,"\n")
print(data[1:2,1:5])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

[[ 7  8  9 10]]


In [56]:
# np.zeros((5,5))
ff=np.ones((5,5))
ff.shape

(5, 5)

In [55]:
print(np.random.rand(1,50).shape)

(1, 50)
